const normalizedGenres = [
  {
    id: "a757a0e9-03c1-4a2a-b384-8ac21dbe2fb2",
    name: "Художественная литература",
    books: [
      "d75f762a-eadd-49be-8918-ed0daa8dd024",
      "uf34kf-dkf74-fjh45-fjgld745-890fghtm",
      "vgoesmdmdil-t6gxr6821ns73tfzrffsyis8",
      "ll8ltm8fhqjxx3lqevm7c0ch3dka-hrn5ast",
      "zssg2jfhel2fimhq06ba1e544p3vqxkv04a2",
      "v3fgm5c4vkpzfnqqqey3k72xiehaetiykacs",
    ],
  },
  {
    id: "bb8afbec-2fec-491f-93e9-7f13950dd80b",
    name: "Нехудожественная литература",
    books: [
      "ch47t3i8jqsfn47s1qgtg899ppm7hegb7waq",
      "xutvigizds17usd5bzaar6edrd19n7y5xfme",
      "ebrol6e3qooac8-n2ij5p6gj6-h8-ohwbn0g",
      "a-seb8pftmyt0grb7r0ig6vghdm4ozbse8eo",
      "1ewa9xr3cr0p7e9wkmo0wyu5hfu60gcczm41",
      "nxk25e7ovb95d3va124b0e9u610ngzxz00cl",
    ],
  },
  {
    id: "982bfbce-c5e0-41a0-9f99-d5c20ecee49d",
    name: "Книги для детей",
    books: [
      "8uxiyykvtqzjg9fang1mllyk93gx-ww8ulex",
      "w6tifz0ocm5pcwg8ik2gcz-ecghysw7wkbsi",
      "q2q6pg7kb-nuvyvhawwv3zb-2mp-t1z5gn-u",
      "xg3dieqr3dplto09alei2bgwf9dc3eci1l1p",
      "810ep6aw2z7q8fn3k6z4h-k7si2t6kszfbvn",
      "rasab11ty2xrpvtxjdn498ndjgcd-xbr1use",
    ],
  },
  {
    id: "wk3fo9ue7d8bvhj5y0crbmz-fknczvej4upm",
    name: "Переодические издания",
    books: [
      "pdfi97b9gku448jf99sv0iku69l01aeb0sf9",
      "usxzg3-gb2ehdor9g5lsg16oq0fxzqsm1550",
      "iw-1u4g0ciq-tom9z04-89g5p5j6ham3vn94",
      "3no7zbetxb7l3bbqqkw-37n8qa49uskhaung",
      "bysl708msmac3tuqup1m7343sbo1x9c5t5tz",
      "w8-xp011kc641siqty6t7m6h04jna66tl132",
    ],
  },
  {
    id: "u0jrfed4ghiysh12vixnlczmboev83e-dn85",
    name: "Религия",
    books: [
      "uxbf73800t561nsek-ch02cgcqbaixd2gg0p",
      "-ni2mwupcgq1z8zfbowlmy72miaqjjdtkn8w",
      "kjufr6o8v74j4w-s55r1lnvl7z2q3-m3q76j",
      "nws9r1ug4vcsykmdeju7ofjtx4fg8mq99atu",
      "04sl63cepz3uxvox34df3n44v63u3cfdbpaq",
      "36pkebdoe4jv2m1w7i8qp26rys8cbl7pxbxd",
    ],
  },
  {
    id: "d7ztgc02ld3j8oxhr1mwv6ghogmw7lkblkh1",
    name: "Учебная литература",
    books: [
      "lhe62sjmwz1vxvt3u53m4b27h4m6n7ae0c95",
      "3mr1lyvogqbi0r3fii946odu-tn-tec05np-",
      "hej-mkub2c0of7q3gsvcjlau12u--nr-h7x6",
      "e6d6fjux9-x5kr1i8vo7hjuvl58gslen9r4t",
      "9mbbyg4u9a-z3n8o0udu39je-ic9oqvnmnzn",
      "zr10odteje7-cjyf8s97ygsglyvgijpxrnzw",
    ],
  },
  {
    id: "-um7o-fxt3qb8cr-4cbvke3q4agbjxnde401",
    name: "Комиксы",
    books: [
      "bmvcx-cdwm7umbcl2abwcz7-0k-br8f6akd4",
      "4690awdg9-fo9jrlobfsj8yozsup17wbo1yr",
      "wl7romdpg2urtgrihglbe37o03tviyfy6z8o",
      "2myafi1j5h8i4e2adpvi6byyf5gdsp5n41li",
      "bxko3k2hidefpuvyoucudi-6ri17aubrbbz9",
      "6urrzhqism6oy8bg-q0owr4kzd2eg-gwllx0",
    ],
  },
];

const normalizedBooks = [
  {
    id: "d75f762a-eadd-49be-8918-ed0daa8dd024",
    name: "Мастер и Маргарита",
    description:
      "\"Мастер и Маргарита» – блистательный шедевр, созданный Михаилом Булгаковым, завораживающая мистическая дьяволиада, обнажающая вечные темы любви, борьбы добра со злом, смерти и бессмертия. Эта книга – на века, она не теряет своей привлекательности; прочтя первую фразу: \"В час жаркого весеннего заката на Патриарших прудах появились двое граждан…», мы добровольно, неминуемо и безвозвратно погружаемся в мир Мастера, Маргариты, Пилата, Воланда, Азазелло с Коровьевым и других героев романа.",
    author: "Михаил Булгаков",
    genre: "Роман",
    price: 600,
    review: 5,
    reviews: [
      "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
      "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
      "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
      "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
      "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "uf34kf-dkf74-fjh45-fjgld745-890fghtm",
    name: "1984",
    description:
      "Одна из самых знаменитых антиутопий XX века – роман \"1984» английского писателя Джорджа Оруэлла (1903–1950) был написан в 1948 году и продолжает тему \"преданной революции», раскрытую в \"Скотном дворе». По Оруэллу, нет и не может быть ничего ужаснее тотальной несвободы. Тоталитаризм уничтожает в человеке все духовные потребности, мысли, чувства и сам разум, оставляя лишь постоянный страх и единственный выбор – между молчанием и смертью, и если Старший Брат смотрит на тебя и заявляет, что \"дважды два – пять», значит, так и есть.",
    author: "Джордж Оруэлл",
    genre: "Фантастика",
    price: 250,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "vgoesmdmdil-t6gxr6821ns73tfzrffsyis8",
    name: "Над пропастью во ржи",
    description:
      "Писатель-классик, писатель-загадка, на пике своей карьеры объявивший об уходе из литературы и поселившийся вдали от мирских соблазнов в глухой американской провинции. Единственный роман Сэлинджера, \"Над пропастью во ржи» стал переломной вехой в истории мировой литературы. И название романа, и имя его главного героя Холдена Колфилда сделались кодовыми для многих поколений молодых бунтарей – от битников и хиппи до современных радикальных молодежных движений.",
    author: "Джером Дэвид Сэлинджер",
    genre: "Роман",
    price: 300,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "ll8ltm8fhqjxx3lqevm7c0ch3dka-hrn5ast",
    name: "Война и мир",
    description:
      "роман-эпопея Льва Николаевича Толстого, описывающий русское общество в эпоху войн против Наполеона в 1805—1812 годах. Эпилог романа доводит повествование до 1820 года.",
    author: "Лев Толстой",
    genre: "Исторический жанр",
    price: 800,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "zssg2jfhel2fimhq06ba1e544p3vqxkv04a2",
    name: "Маленький принц",
    description:
      "В одном из писем к матери Сент-Экзюпери признался: \"Мне ненавистны люди, пишущие ради забавы, ищущие эффектов. Надо иметь что сказать». Ему, романтику неба, не чуравшемуся земных радостей, любившему, по свидетельству друзей, \"писать, говорить, петь, играть, докапываться до сути вещей, есть, обращать на себя внимание, ухаживать за женщинами», человеку проницательного ума со своими достоинствами и недостатками, но всегда стоявшему на защите общечеловеческих ценностей, было \"что сказать». И он написал самую известную во всем мире сказку \"Маленький принц» о самом важном в этой жизни, жизни на планете Земля, все чаще такой неласковой, но любимой и единственной.",
    author: "Антуан де Сент-Экзюпери",
    genre: "Детская литература",
    price: 200,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "v3fgm5c4vkpzfnqqqey3k72xiehaetiykacs",
    name: "Унесённые ветром",
    description:
      "Работа над произведением продолжалась около десяти лет и потребовала от писательницы огромной самоотдачи и напряженного труда. Стремясь проникнуть в самый дух эпохи, Митчелл кропотливо изучала историю родной Атланты, использовала газеты и журналы середины XIX века. На страницах ее рукописи оживали рассказы очевидцев Гражданской войны и семейные предания. Некоторые сцены Митчелл переписывала по четыре-пять раз, а что касается первой главы, писательницу удовлетворил лишь 60-й вариант!",
    author: "Маргарет Митчелл",
    genre: "Роман",
    price: 400,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "ch47t3i8jqsfn47s1qgtg899ppm7hegb7waq",
    name: "Хочу и буду",
    description: "Психолог Михаил Лабковский абсолютно уверен, что человек может и имеет право быть счастливым и делать только то, что он хочет. Его книга о том, как понять себя, обрести гармонию и научиться радоваться жизни.",
    author: "Михаил Лабковский",
    genre: "Мотивация",
    price: 350,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "xutvigizds17usd5bzaar6edrd19n7y5xfme",
    name: "Тонкое искусство пофигизма",
    description: "Современное общество пропагандирует культ успеха: будь умнее, богаче, продуктивнее – будь лучше всех. Соцсети изобилуют историями на тему, как какой-то малец придумал приложение и заработал кучу денег, статьями в духе \"Тысяча и один способ быть счастливым», а фото во френдленте создают впечатление, что окружающие живут лучше и интереснее, чем мы. Однако наша зацикленность на позитиве и успехе лишь напоминает о том, чего мы не достигли, о мечтах, которые не сбылись. Как же стать по-настоящему счастливым?",
    author: "Марк Мэнсон",
    genre: "Саморазвитие",
    price: 350,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "ebrol6e3qooac8-n2ij5p6gj6-h8-ohwbn0g",
    name: "Подсознание может все!",
    description: "Использование огромных резервов, скрытых в подсознании каждого человека, позволяет решать самые сложные повседневные проблемы, когда логика оказывается бессильной. Разработанная автором этой книги программа поможет вам активизировать безграничные ресурсы собственного головного мозга, чтобы изменить свою жизнь к лучшему раз и навсегда.",
    author: "Джон Кехо",
    genre: "Саморазвитие",
    price: 300,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "a-seb8pftmyt0grb7r0ig6vghdm4ozbse8eo",
    name: "Сказать жизни 'ДА!'",
    description: "Эта удивительная книга сделала ее автора одним из величайших духовных учителей человечества в XX веке. В ней философ и психолог Виктор Франкл, прошедший нацистские лагеря смерти, открыл миллионам людей всего мира путь постижения смысла жизни. Дополнительный подарок для читателя настоящего издания – пьеса \"Синхронизация в Биркенвальде», где выдающийся ученый раскрывает свою философию художественными средствами.",
    author: "Виктор Франкл",
    genre: "Философия",
    price: 450,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "1ewa9xr3cr0p7e9wkmo0wyu5hfu60gcczm41",
    name: "Самый богатый человек в Вавилоне",
    description: "Автор этой книги уверен: чтобы исполнить все свои замыслы и желания, Вы прежде всего должны добиться успеха в денежных вопросах, используя принципы управления личными финансами, изложенные на её страницах.",
    author: "Клейсон Джорж Самюэль",
    genre: "Мотивация",
    price: 300,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "nxk25e7ovb95d3va124b0e9u610ngzxz00cl",
    name: "Красная таблетка",
    description: "Книга простым языком объясняет читателю, каким образом работает человеческий мозг. Без сложной терминологии автор говорит о самой природе сознания – емко, просто и с долей юмора. Почему мы недооцениваем возможности собственного мозга, неправильно воспринимаем окружающий мир и людей в нем? А главное – почему большинству современников так тяжело найти самих себя? Ответы – в \"Красной таблетке».",
    author: "Андрей Курпатов",
    genre: "Документальный",
    price: 400,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "8uxiyykvtqzjg9fang1mllyk93gx-ww8ulex",
    name: "Денискины рассказы",
    description: "Его чудесный герой Дениска умеет любить, дружить и прощать, нежное и светлое чувство в нём всегда одерживает верх над обманом и обидами. Жизнь мальчишки невероятно интересна: и его дружба с Мишкой, и весёлый школьный карнавал, и смешные происшествия на уроках, и поход в цирк, где выступает необыкновенная девочка на шаре, и появление в семье новорождённой сестрёнки Ксении…",
    author: "Виктор Драгунский",
    genre: "Художественный вымысел",
    price: 200,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "w6tifz0ocm5pcwg8ik2gcz-ecghysw7wkbsi",
    name: "Алиса в Стране чудес",
    description: "В книгу включены две самые известные и популярные сказочные повести английского писателя и математика Льюиса Кэрролла: \"Алиса в Стране Чудес» и \"Алиса в Зазеркалье». Неповторимое своеобразие кэрролловского стиля, необычные ситуации, в которые попадает главная героиня, удивительные превращения, происходящие с ней и забавные герои, с которыми Алиса встречается во время своих путешествий – все это и есть Страна Чудес, край удивительных вопросов и еще более удивительных ответов.",
    author: "Льюис Кэрролл",
    genre: "Детская литература",
    price: 350,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "q2q6pg7kb-nuvyvhawwv3zb-2mp-t1z5gn-u",
    name: "Волшебник Изумрудного города",
    description: "Вы верите, что на свете существуют волшебники и феи? Вы хотите попасть в Волшебную страну? Элли тоже мечтала об этом. Но когда ужасный ураган поднял в воздух ее маленький домик, она очень испугалась. И хорошо, что рядом оказался верный песик Тотошка.",
    author: "Александр Волков",
    genre: "Детская литература",
    price: 500,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "xg3dieqr3dplto09alei2bgwf9dc3eci1l1p",
    name: "Приключения Тома Сойера",
    description: "В книге о приключениях Тома Сойера писатель с большим мастерством нарисовал жизнь американского провинциального городка 40-х годов XIX века. Благодаря напряженному сюжету и блестящему юмору эта книга горячо любима читателями всего мира.",
    author: "Марк Твен",
    genre: "Детская литература",
    price: 450,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "810ep6aw2z7q8fn3k6z4h-k7si2t6kszfbvn",
    name: "Винни-Пух и все-все-все",
    description: "\"Винни-Пух и все-все-все\" - две повести о забавном медвежонке по имени Винни-Пух, его друзьях и приключениях, которые поджидают их в таинственном Зачарованном Лесу.",
    author: "Алан Александр Милн",
    genre: "Художественный вымысел",
    price: 350,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "rasab11ty2xrpvtxjdn498ndjgcd-xbr1use",
    name: "Приключения Незнайки и его друзей",
    description: "\"Приключения Незнайки и его друзей\" – первая книга в трилогии знаменитого писателя Николая Носова о приключениях Незнайки. Опубликованная в середине прошлого века, она вошла в золотой фонд детской литературы.",
    author: "Николай Носов",
    genre: "Роман-сказка",
    price: 500,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "pdfi97b9gku448jf99sv0iku69l01aeb0sf9",
    name: "Комсомольская правда",
    description: "\"Комсомольская правда\" — советская и российская ежедневная общественно-политическая газета, а также интернет-издание, радиостанция и телеканал. Входят в издательский дом \"Комсомольская правда». Газета основана 13 марта 1925 года как официальный печатный орган ВЛКСМ. Первый номер вышел 24 мая 1925 года.",
    author: "Владимир Сунгоркин",
    genre: "Газета",
    price: 150,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "usxzg3-gb2ehdor9g5lsg16oq0fxzqsm1550",
    name: "Коммерсантъ",
    description: "\"Коммерсантъ-Daily\" — российская ежедневная общественно-политическая газета с усиленным деловым блоком. Выпускается издательским домом \"Коммерсантъ». Периодичность — шесть раз в неделю. Объём — 12 страниц. В субботнем номере публикуются объявления о банкротстве, в связи с чем он может достигать 200 и более страниц",
    author: "Артур Саркисян",
    genre: "Газета",
    price: 200,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "iw-1u4g0ciq-tom9z04-89g5p5j6ham3vn94",
    name: "The New York Times",
    description: "The New York Times, традиционная транскрипция — \"Нью-Йорк таймс\" — американская ежедневная газета, издающаяся в Нью-Йорке с 18 сентября 1851 года. Третья по тиражу газета в стране после USA Today и The Wall Street Journal и 40-я в мире.",
    author: "Дин Баке",
    genre: "Газета",
    price: 300,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "3no7zbetxb7l3bbqqkw-37n8qa49uskhaung",
    name: "The Wall Street Journal",
    description: "\"Уолл-стрит джорнэл» — ежедневная американская деловая газета на английском языке. Издаётся в Нью-Йорке компанией Dow Jones & Company, которая входит в холдинг News Corp, с 1889. \"Уолл-стрит джорнэл» — одно из крупнейших и влиятельнейших американских изданий.",
    author: "Чарльз Доу",
    genre: "Газета",
    price: 250,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "bysl708msmac3tuqup1m7343sbo1x9c5t5tz",
    name: "Playboy",
    description: "\"Плейбо́й» — эротический журнал для мужчин, издающийся с 1953 года Хью Хефнером и его коллегами, выросший в издательский дом Playboy Enterprises, деятельность которого простирается на многие области медиа-бизнеса для взрослых. Кроме журнала в США выпускаются журналы на различных языках во всём мире.",
    author: "Хью Хефнер",
    genre: "Журнал",
    price: 350,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "w8-xp011kc641siqty6t7m6h04jna66tl132",
    name: "TIME",
    description: "Time — американский еженедельный журнал и информационный портал со штаб-квартирой в Нью-Йорке. Впервые номер журнала вышел в Нью-Йорке 3 марта 1923 года; долгие годы журнал издавался одним из его основателей, Генри Люсом.",
    author: "Нэнси Гиббс",
    genre: "Журнал",
    price: 300,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "uxbf73800t561nsek-ch02cgcqbaixd2gg0p",
    name: "Библия",
    description: "Би́блия — собрание текстов, являющихся священными в иудаизме и христианстве и составляющих Священное Писание в этих религиях. В иудаизме Священным Писанием является Танах, именуемый также еврейской Библией; в христианстве — Ветхий Завет, состоящий из книг Танаха и дополнительных священных книг, и Новый Завет.",
    author: "",
    genre: "Священный текст",
    price: 800,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "-ni2mwupcgq1z8zfbowlmy72miaqjjdtkn8w",
    name: "Танах",
    description: "Тана́х — принятое в иврите название еврейской Библии, акроним названий трёх её разделов. Термин \"Танах» вошёл в употребление в Средние века. Тексты Танаха написаны изначально в основном на древнееврейском языке, с некоторыми отрывками на древнеарамейском. Включает разделы: То́ра — Пятикнижие; Невии́м — Пророки.",
    author: "",
    genre: "Священный текст",
    price: 600,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "kjufr6o8v74j4w-s55r1lnvl7z2q3-m3q76j",
    name: "Коран",
    description: "Кора́н — священная книга мусульман, написанная на арабском языке. Слово \"Коран» происходит от арабского الْقُرآن — \"чтение вслух», \"назидание». Согласно исламскому вероучению, Коран был передан путём откровения пророку Мухаммеду и является словом Божьим и Последним Заветом для человечества.",
    author: "Мухаммед",
    genre: "Священный текст",
    price: 700,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "nws9r1ug4vcsykmdeju7ofjtx4fg8mq99atu",
    name: "Бхагавад-гита",
    description: "\"Бхагавадги́та» — памятник древнеиндийской религиозно-философской мысли на санскрите, часть шестой книги \"Махабхараты», состоит из 18 глав и 700 стихов. Один из базовых текстов индуистской философии.",
    author: "Борис Гребенщиков",
    genre: "Философия",
    price: 350,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "04sl63cepz3uxvox34df3n44v63u3cfdbpaq",
    name: "О сопротивлении злу силой",
    description: "\"О сопротивлении злу силой» — книга философа И. А. Ильина, написанная в 1925 году. Относится к берлинскому периоду творчества философа. Произведение посвящено участникам белого движения и направлено на критику учения Л. Н. Толстого и его последователей о ненасилии.",
    author: "Иван Ильин",
    genre: "Философия",
    price: 300,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "36pkebdoe4jv2m1w7i8qp26rys8cbl7pxbxd",
    name: "Война и вера",
    description: "Книга \"Война и вера» – это сборник потрясающих реальных историй, рассказанных воинами и мирными людьми, жизнь которых на войне спасли по их вере и молитве (часто неискусной, но идущей из глубины души) Пресвятая Богородица, святые и сила Креста Христова. Лейтмотивом через все повествование проходит призыв не бояться убивающих тело (см. Мф. 10, 28; Лк. 12, 4), но побеждать их верой в любовь и силу правды Божией.",
    author: "Вольный Странник",
    genre: "Философия",
    price: 250,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "lhe62sjmwz1vxvt3u53m4b27h4m6n7ae0c95",
    name: "Патопсихология",
    description: "Данный учебник первое издание в отечественной психологии, содержащее в систематизированном виде целостное представление о патопсихологии как особой области знания. В нем обсуждается вопрос о месте патопсихологии в системе других наук, о значении патопсихологических исследований для решения общетеоретических проблем психологии. В книге представлена систематизация нарушений сознания, личности, восприятия, памяти, мышления, умственной работоспособности. Описано изучение психических расстройств экспериментально-психологическими методами.",
    author: "Блюма Зейгарник",
    genre: "Учебник",
    price: 300,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "3mr1lyvogqbi0r3fii946odu-tn-tec05np-",
    name: "Секреты орфографии",
    description: "Авторы книги в занимательной, доступной для учащихся форме рассказывают об основных орфографических правилах русского языка. Рассказ сопровождается заданиями с ключами (ответами), играми, красочными иллюстрациями. Поэтому книга может быть использована как учебное пособие и на уроке, и во внеклассной работе.",
    author: "Генриетта Граник",
    genre: "Учебник",
    price: 450,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "hej-mkub2c0of7q3gsvcjlau12u--nr-h7x6",
    name: "История России с древнейших времен до конца XVII века",
    description: "\"История России с древнейших времен до конца XVII века\" - уникальное учебное пособие, созданное коллективом авторов под редакцией А.В.Милова. В издании предпринята попытка проследить воздействие природно-климатического и географического факторов на протяжении столетий не только на социально-экономическую жизнь страны, но и их влияние на государствен.",
    author: "Леонид Милов",
    genre: "Учебник",
    price: 500,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "e6d6fjux9-x5kr1i8vo7hjuvl58gslen9r4t",
    name: "Биохимия",
    description: "В учебнике рассмотрены основные положения классической биохимии. Приведены сведения о структуре и свойствах биомолекул, биоэнергетике, молекулярных основах физиологических функций человека.",
    author: "Сергей Северин",
    genre: "Учебник",
    price: 350,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "9mbbyg4u9a-z3n8o0udu39je-ic9oqvnmnzn",
    name: "Современный русский язык",
    description: "Пособие содержит все разделы курса современного русского языка и написано в полном соответствии с программой для факультетов филологического профиля. Теоретический материал излагается с использованием традиционных лингвистических терминов. Спорные вопросы теории русского языка освещаются с разных точек зрения. Все положения иллюстрируются примерами из русской классической и современной прозы, поэзии и публицистики. Даны упражнения и вопросы для закрепления материала.",
    author: "Дитмар Розенталь",
    genre: "Справочник",
    price: 300,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "zr10odteje7-cjyf8s97ygsglyvgijpxrnzw",
    name: "О русских именах",
    description: "В книге в популярной форме рассказывается об истории русских имен, отчеств и фамилий. Приводятся официальные и неофициальные, полные и сокращенные формы, даются церковные и народные варианты, редкие, малоизвестные и новые имена.",
    author: "Александра Суперанская",
    genre: "Учебник",
    price: 250,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "bmvcx-cdwm7umbcl2abwcz7-0k-br8f6akd4",
    name: "Хранители",
    description: "Не надо быть энтузиастом массовой культуры, чтобы по первым двадцати страницам понять, что ХРАНИТЕЛИ - образец высокого, очень высокого искусства; а уж что будет на следующих двадцати... Не удивительно, что именно этот роман чаще прочих оказывается на верхней строчке в списках \"комиксов для людей, которые не читают комиксы\".",
    author: "Алан Мур",
    genre: "Комикс",
    price: 200,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "4690awdg9-fo9jrlobfsj8yozsup17wbo1yr",
    name: "Бэтмен. Убийственная шутка",
    description: "\"Чтобы превратить самого здравого человека на свете в полного психа, нужен всего один плохой день», — утверждает Джокер. Он снова сбежал из лечебницы Аркхем — лишь для того, чтобы доказать этот тезис. А помочь ему должны, сами того не желая, комиссар полиции Джим Гордон и его красавица-дочь Барбара.",
    author: "Алан Мур",
    genre: "Комикс",
    price: 350,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "wl7romdpg2urtgrihglbe37o03tviyfy6z8o",
    name: "Сказки",
    description: "Представьте себе, что все наши самые любимые сказки оказались реальными людьми и поселились среди нас, сохранив все свои волшебные свойства. Как им удастся выжить в нашем обыкновенном, лишенном колдовства мире?",
    author: "Билл Уиллингхэм",
    genre: "Комикс",
    price: 150,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "2myafi1j5h8i4e2adpvi6byyf5gdsp5n41li",
    name: "Ходячие мертвецы",
    description: "На смену миру торговли и пустого потребительства пришел мир выживания и ответственности. Эпидемия апокалиптических масштабов прокатилась по планете, пробудив мёртвых, которые начали пожирать живых. За несколько месяцев человеческое общество было разрушено. Исчезли правительства, магазины, доставка почты, кабельное телевидение. В мире, где правят мёртвые, мы наконец вынуждены начать жить.",
    author: "Роберт Киркман",
    genre: "Комикс",
    price: 300,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "bxko3k2hidefpuvyoucudi-6ri17aubrbbz9",
    name: "Скотт Пилигрим",
    description: "Жизнь Скотта Пилигрима прекрасна. Ему 23 года, он играет в группе, \"временно без работы\" и встречается с прелестной старшеклассницей. Всё было отлично, пока сквозь его сны не начала разъезжать на роликах мозгоразрывающе модная девчонка-курьер по имени Рамона Флауэрс. Но путь к сердцу Рамоны не усеян розовыми лепестками: на пути у Скотта стоят её семеро злых бывших. Сумеет ли Скотт разделаться с плохими ребятами и достичь счастья, не поставив всю свою маленькую прекрасную жизнь на уши?",
    author: "Брайан Ли О'Мэлли",
    genre: "Комикс",
    price: 300,
    review: 4,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
  {
    id: "6urrzhqism6oy8bg-q0owr4kzd2eg-gwllx0",
    name: "Песочный человек",
    description: "\"Сэндмену» недаром нет равных среди графических романов по числу наград и премий, равно как и по числу похвальных отзывов. \"Сэндмен» — это полный тайн и открытий сюжет с философским подтекстом, прописанным гениальным пером Нила Геймана и иллюстрированный лучшими художниками, \"Сэндмен» — это колдовская смесь мифа и темной фэнтези, где сплетаются воедино множество жанров. Подобных саг,где одна таинственная история плавно перетекает в другую, не менее таинственную, мир графических романов прежде не видел. Однажды прочитав, \"Сэндмена» невозможно забыть.",
    author: "Нил Гейман",
    genre: "Комикс",
    price: 250,
    review: 5,
    reviews: [
        "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
        "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
        "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
        "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
        "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    ],
  },
];

const normalizedReviews = [
  {
    id: "9hichidsgzqvynxvaire08ynwm-jr6ikwnh9",
    userId: "oe76r0woz2cqohp3yjowv24i9bhb34bxg5q0",
    text: '"Мастер и Маргарита" на мой взгляд - лучшее произведение Булгакова. Книга-легенда, которую стоит читать. В ней завораживает всё: язык автора, его юмор, постоянно сменяющиеся эпизоды, в которых раскрывается и тема религии, и человеческих пороков, и отношение автора к советскому союзу. Книга захватывает, её не возможно не дочитать.',
    review: 5,
  },
  {
    id: "cuaeo-5im0vqia6znfgvxl7otyq99b0ay3dp",
    userId: "emzi1twghrhkow0bxihiq8hpvpdud4o8cpv1",
    text: "Не знаю, кому как, а как по мне, так это вообще лучший роман всех времен! Не только фантастический, вообще. В книге есть все: идея, композиция, великолепно проработанные герои, замечательный юмор, увлекательный сюжет. Жаль, что Михаил Афанасьевич сподобился написать только одно произведение ТАКОГО уровня. Остальные его книги послабее. Но даже один только \"Мастер» поднимает писателя на немыслимую для современных авторов высоту!",
    review: 5,
  },
  {
    id: "8sedro51b0d7majsxnra2bd-ljoq7diyfxg6",
    userId: "0npa5238ulgh89sel1rqbni4286ni0rwk4dp",
    text: "Потрясающая книга!!! Читала раз десять и каждый раз интересно, и каждый раз по-новому. Конечно же, в моем ТОПе. Это любовь!",
    review: 5,
  },
  {
    id: "gezas3124ntvbyoo3tc7ja7xhxi9wvxarh-4",
    userId: "uctbnpj9lz4psg2eesvszauq7-gdbjknyz38",
    text: "Потрясающая классика, которая захватывает с первой же главы и не теряет своей актуальности и по сей день! И приятный конец. Как говорится за тьмой всегда приходит рассвет!",
    review: 5,
  },
  {
    id: "xss44g9l0zsvfnpmr35thzt-kw05k8uwm9e2",
    userId: "k7riyq035jmwyx73703qu1zunquxwpdty-7h",
    text: "Вечная борьба двух взаимоисключающих начал- добра и зла, дня и ночи, мужчины и женщины,бога и дьявола, жизни и смерти. В этом противостоянии никогда не будет ни победителей, ни побеждённых, ибо сама вселенная есть хаос и порядок одновременно. По истине бессмертное произведение классика русской литературы всегда будет вне времени и пространстве ибо \"рукописи не горят»",
    review: 5,
  },
];

const normalizedUsers = [
  {
    id: "oe76r0woz2cqohp3yjowv24i9bhb34bxg5q0",
    name: "Александра",
  },
  {
    id: "emzi1twghrhkow0bxihiq8hpvpdud4o8cpv1",
    name: "Редкина Ирина",
  },
  {
    id: "0npa5238ulgh89sel1rqbni4286ni0rwk4dp",
    name: "Анна Тати",
  },
  {
    id: "uctbnpj9lz4psg2eesvszauq7-gdbjknyz38",
    name: "Анна Лазарева",
  },
  {
    id: "k7riyq035jmwyx73703qu1zunquxwpdty-7h",
    name: "Павел Хайленко",
  },
];

module.exports = {
  books: normalizedBooks,
  genres: normalizedGenres,
  reviews: normalizedReviews,
  users: normalizedUsers,
};
